### ISSUE TITLE
 C compiler failed while compiling BRKey.c !!

### ISSUE THREAD

**Issue by mmmce1994** [breadwallet/breadwallet-android#12]
hi every one !
when i rebuild project,i faced with this error :

Error:Execution failed for task ':app:compileCoreMipsDebugSharedLibraryCoreMipsDebugSharedLibraryMainC'.
> A build operation failed.
      C compiler failed while compiling BRKey.c.
  See the complete log at: file:///C:/Users/PC4/AndroidStudioProjects/breadwallet-android-master/app/build/tmp/compileCoreMipsDebugSharedLibraryCoreMipsDebugSharedLibraryMainC/output.txt

any idea ?

**Comment by Gutyn** [comment]
Hi, @mmmce1994, please make sure you update the submodules, and please share the error contained in your output.txt.

**Comment by mmmce1994** [comment]
i downloaded project (not clone) & submodules as zip files manually form github and build project !
(git submodule update and init) return blank ,so i can not use them !
i think if (git submodules init and update) work correctly, the problem will be solved .
please help me how to use (git submodule update and init) that work correct and not return blank ??

**Comment by mmmce1994** [comment]
hi, @Gutyn , please help me ! is there any solution ?

**Comment by Gutyn** [comment]
Hi, @mmmce1994 I am looking into it right now, will try to reproduce your problem.

**Comment by Gutyn** [comment]
Hi, @mmmce1994 please try the latest push that might fix the problem.
Seems like it's a clang bug but I am not sure yet.
Please let me know if it works.

**Comment by mmmce1994** [comment]
Hi @Gutyn ,thanks for ur help,the error has bin solved !
when i am running the app using usb debugging , the app installed,but it crashed and did not run !

**Comment by Gutyn** [comment]
Hi @mmmce1994, very glad I could help. Let me know what is the crashing log in another issue, and I will try to help.

**Comment by mmmce1994** [comment]
there is no log, just "unfortunately-app-has-stopped"!!

**Comment by Gutyn** [comment]
If you ran the app in Android Studio, then go to android console, and see the logs of the app. Please find in the logs the reason it crashed.

**Comment by mmmce1994** [comment]
E/UncaughtException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr" referenced by "/data/app/com.breadwallet-1/lib/arm/libcore.so"...
                                                          at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                          at java.lang.System.loadLibrary(System.java:1076)
                                                          at com.breadwallet.presenter.activities.IntroActivity.<clinit>(IntroActivity.java:82)
                                                          at java.lang.Class.newInstance(Native Method)
                                                          at android.app.Instrumentation.newActivity(Instrumentation.java:1096)
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3122)
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:148)
                                                          at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-24 13:27:34.048 21642-21642/? E/HealthDataStore: disconnectService: Context instance is invalid

**Comment by Gutyn** [comment]
Please try to clean the project Build -> Clean Project.
If that won't fix the problem then please try another device/emulator.

**Comment by mmmce1994** [comment]
This two solutions did not work also !! 
Any other idea ?

**Comment by Gutyn** [comment]
Take a look at this:
https://github.com/android-ndk/ndk/issues/126
Let me know if it helps.

**Comment by mmmce1994** [comment]
please tell me which version of NDK do u use ?

**Comment by Gutyn** [comment]
I use r11c.
