### ISSUE TITLE
Fetcher: Failed to update currency and rate data

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#158]
I am having this error in the latest master branch, could someone show the instructions to make this api to work?

```
E/RatesFetcher$start: Failed to update currency and rate data
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.breadwallet.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:184)
        at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:81)
        at com.google.firebase.remoteconfig.ktx.RemoteConfigKt.getRemoteConfig(RemoteConfig.kt:30)
        at com.breadwallet.tools.manager.RatesFetcher.getFixedRates(RatesFetcher.kt:163)
        at com.breadwallet.tools.manager.RatesFetcher.updateRates(RatesFetcher.kt:150)
        at com.breadwallet.tools.manager.RatesFetcher$updateRates$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by DrewCarlson** [comment]
Thanks for the report.  We will fix this in an upcoming release.

https://github.com/breadwallet/breadwallet-android/blob/e2d184805dfde8043d2ec33b2f6860280f494d15/app/src/main/java/com/breadwallet/tools/manager/RatesFetcher.kt#L150

This line should be guarded with `BuildConfig.USE_REMOTE_CONFIG` or it will attempt to access firebase which always fails when cloned from github.  For now you can add the check manually or just remove that line.

**Comment by dabitdev** [comment]
thank you @DrewCarlson, when is the expected upcoming release coming?

**Comment by DrewCarlson** [comment]
Fixed by https://github.com/breadwallet/breadwallet-android/pull/166/commits/363fb8c483c3347517a700e5fea4b0c794904345.
