### ISSUE TITLE
Wallet is not showing total assets value (fiat) of coins when firebase is not initialized.

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#173]
```
2020-10-15 14:23:16.296 7213-7344/cash.just.debug E/RatesFetcher$start: Failed to update currency and rate data
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process cash.just.debug. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(FirebaseApp.java:184)
        at com.google.firebase.remoteconfig.FirebaseRemoteConfig.getInstance(FirebaseRemoteConfig.java:81)
        at com.google.firebase.remoteconfig.ktx.RemoteConfigKt.getRemoteConfig(RemoteConfig.kt:30)
        at com.breadwallet.tools.manager.RatesFetcher.getFixedRates(RatesFetcher.kt:163)
        at com.breadwallet.tools.manager.RatesFetcher.updateRates(RatesFetcher.kt:150)
        at com.breadwallet.tools.manager.RatesFetcher$updateRates$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by dabitdev** [comment]
my bad this was already fixed
