### ISSUE TITLE
Upgrade from 4.1.1 to 4.5.8

### ISSUE THREAD

**Issue by dabitdev** [breadwallet/breadwallet-android#179]
- the apps asks the user to enter an new pin an to reenter
- then the wallet is empty
- after a few restarts the app is able to upgrade

```
2020-11-11 12:53:51.582 31351-31461/cash.just.wallet.debug W/AndroidKeysetManager: keyset not found, will generate a new one
    java.io.FileNotFoundException: can't read keyset; the pref value __androidx_security_crypto_encrypted_prefs_key_keyset__ does not exist
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readPref(SharedPrefKeysetReader.java:71)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.readEncrypted(SharedPrefKeysetReader.java:89)
        at com.google.crypto.tink.KeysetHandle.read(KeysetHandle.java:105)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:304)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:280)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:230)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:121)
        at com.breadwallet.app.BreadApp.createEncryptedPrefs(BreadApp.kt:529)
        at com.breadwallet.app.BreadApp.access$createEncryptedPrefs(BreadApp.kt:127)
        at com.breadwallet.app.BreadApp$kodein$2$3$1.invoke(BreadApp.kt:300)
```

**Comment by dabitdev** [comment]
`BRDUserManager.migrateKeystoreData()` crashes with NPE on `BRKeyStore.getToken`

**Comment by dabitdev** [comment]
I just fixed using the `oldBRKeystore` and doing the migration using their methods.
